hmm = {
    "items_list": [
        {
            "autoPay": "false",
            "condition": {
                "conditionDisplayName": "For parts " "or not " "working",
                "conditionId": "7000",
            },
            "country": "US",
            "galleryURL": "https://i.ebayimg.com/thumbs/images/g/J60AAOSw6hZhMUi3/s-l140.jpg",
            "globalId": "EBAY-US",
            "isMultiVariationListing": "false",
            "itemId": "165050522770",
            "listingInfo": {
                "bestOfferEnabled": "true",
                "buyItNowAvailable": "false",
                "endTime": "2021-10-02T22:02:43.000Z",
                "gift": "false",
                "listingType": "FixedPrice",
                "startTime": "2021-09-02T22:02:43.000Z",
                "watchCount": "1",
            },
            "location": "Makawao,HI,USA",
            "postalCode": "967**",
            "primaryCategory": {
                "categoryId": "139971",
                "categoryName": "Video Game " "Consoles",
            },
            "productId": {"_type": "ReferenceID", "value": "100236301"},
            "returnsAccepted": "false",
            "sellingStatus": {
                "convertedCurrentPrice": {
                    "_currencyId": "USD",
                    "value": "55.0",
                },
                "currentPrice": {"_currencyId": "USD", "value": "55.0"},
                "sellingState": "Active",
                "timeLeft": "P0DT0H0M49S",
            },
            "shippingInfo": {
                "expeditedShipping": "true",
                "handlingTime": "3",
                "oneDayShippingAvailable": "false",
                "shipToLocations": "Worldwide",
                "shippingType": "Calculated",
            },
            "title": "Sony PlayStation 2 Black Home Console Lot",
            "topRatedListing": "false",
            "viewItemURL": "https://www.ebay.com/itm/Sony-PlayStation-2-Black-Home-Console-Lot-/165050522770",
        },
        {
            "autoPay": "true",
            "condition": {
                "conditionDisplayName": "Used",
                "conditionId": "3000",
            },
            "country": "US",
            "galleryURL": "https://i.ebayimg.com/thumbs/images/g/QckAAOSwvRFguAC6/s-l140.jpg",
            "globalId": "EBAY-US",
            "isMultiVariationListing": "false",
            "itemId": "154477783194",
            "listingInfo": {
                "bestOfferEnabled": "false",
                "buyItNowAvailable": "false",
                "endTime": "2021-10-02T22:05:50.000Z",
                "gift": "false",
                "listingType": "FixedPrice",
                "startTime": "2021-06-02T22:05:50.000Z",
                "watchCount": "3",
            },
            "location": "Montrose,CO,USA",
            "postalCode": "814**",
            "primaryCategory": {
                "categoryId": "139971",
                "categoryName": "Video Game " "Consoles",
            },
            "returnsAccepted": "true",
            "sellingStatus": {
                "convertedCurrentPrice": {
                    "_currencyId": "USD",
                    "value": "37.99",
                },
                "currentPrice": {"_currencyId": "USD", "value": "37.99"},
                "sellingState": "Active",
                "timeLeft": "P0DT0H3M56S",
            },
            "shippingInfo": {
                "expeditedShipping": "true",
                "handlingTime": "1",
                "oneDayShippingAvailable": "false",
                "shipToLocations": "Worldwide",
                "shippingServiceCost": {"_currencyId": "USD", "value": "0.0"},
                "shippingType": "Free",
            },
            "title": "Hori White Playstation 1 Controller OEM "
            "PS1 Japan Import US Seller RARE 1PD03",
            "topRatedListing": "true",
            "viewItemURL": "https://www.ebay.com/itm/Hori-White-Playstation-1-Controller-OEM-PS1-Japan-Import-US-Seller-RARE-1PD03-/154477783194",
        },
        {
            "autoPay": "true",
            "condition": {
                "conditionDisplayName": "Used",
                "conditionId": "3000",
            },
            "country": "US",
            "galleryURL": "https://i.ebayimg.com/thumbs/images/g/-ZEAAOSwTdxhMUrg/s-l140.jpg",
            "globalId": "EBAY-US",
            "isMultiVariationListing": "false",
            "itemId": "393548135843",
            "listingInfo": {
                "bestOfferEnabled": "false",
                "buyItNowAvailable": "false",
                "endTime": "2021-10-02T22:06:26.000Z",
                "gift": "false",
                "listingType": "FixedPrice",
                "startTime": "2021-09-02T22:06:26.000Z",
            },
            "location": "White Bluff,TN,USA",
            "postalCode": "371**",
            "primaryCategory": {
                "categoryId": "139971",
                "categoryName": "Video Game " "Consoles",
            },
            "returnsAccepted": "false",
            "sellingStatus": {
                "convertedCurrentPrice": {
                    "_currencyId": "USD",
                    "value": "142.0",
                },
                "currentPrice": {"_currencyId": "USD", "value": "142.0"},
                "sellingState": "Active",
                "timeLeft": "P0DT0H4M32S",
            },
            "shippingInfo": {
                "expeditedShipping": "true",
                "handlingTime": "2",
                "oneDayShippingAvailable": "false",
                "shipToLocations": "Worldwide",
                "shippingType": "Calculated",
            },
        },
    ],
}
